apiVersion: apps/v1
kind: Deployment
metadata:
  name: peaks
  namespace: kube-system
  labels:
    component: peaks
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peaks
  template:
    metadata:
      labels:
        component: peaks
    spec:
      serviceAccount: peaks-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
        - name: kubeconfig
          hostPath:
            path: /var/lib/microshift/resources/kubeadmin/kubeconfig
            type: File 
      containers:
        - name: scheduler-ctrl
          image: quay.io/sustainable_computing_io/peaks:latest
          imagePullPolicy: IfNotPresent
          args:
            - /usr/bin/peaks
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
            - name: kubeconfig
              mountPath: /var/lib/kubeconfig
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: /var/lib/kubeconfig
    profiles:
    - schedulerName: Peaks
      plugins:
        score:
          enabled:
          - name: "Peaks"
          disabled:
          - name: "*"